name:                Cracker
version:             0.1.0.0
github:              "Federickg23/seedCracker"
license:             BSD3
author:              "Justin Chen & Federick Gonzalez"
maintainer:          "example@example.com"
copyright:           "2021 Justin Chen & Federick Gonzalez"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Federickg23/seedCracker#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Cracker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Cracker

tests:
  Cracker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Cracker
